In [52]:
import pandas as pd
import numpy as np
from sklearn import linear_model

In [53]:
df = pd.read_csv('property-price.csv')
df

Area (sqr ft)  Bedroom  Age   Price
0           2600      3.0   20  550000
1           3000      4.0   15  565000
2           3200      3.5   18  610000
3           3600      3.0   30  595000
4           4000      5.0    8  760000
5           2200      2.0   10  510000
6           1500      2.0    5  480000
7           1000      2.0   10  500000
8           1600      2.0   12  480000
9           2700      4.0   11  600000

In [54]:
X = df.drop(['Price'], axis= 1)
y = df[['Price']]

In [55]:
X


Area (sqr ft)  Bedroom  Age
0           2600      3.0   20
1           3000      4.0   15
2           3200      3.5   18
3           3600      3.0   30
4           4000      5.0    8
5           2200      2.0   10
6           1500      2.0    5
7           1000      2.0   10
8           1600      2.0   12
9           2700      4.0   11

In [56]:
y

Price
0  550000
1  565000
2  610000
3  595000
4  760000
5  510000
6  480000
7  500000
8  480000
9  600000

In [57]:
model = linear_model.LinearRegression()
model.fit(X,y)

LinearRegression()

In [58]:
model.coef_

array([[   56.27656262, 31333.51709201, -2539.43847995]])

In [59]:
model.intercept_

array([361788.49869726])

In [62]:
pred = model.predict(X)
pred

array([[551319.34317466],
       [617860.6777126 ],
       [605830.91624985],
       [582201.52099069],
       [723246.82677973],
       [522869.58583591],
       [496173.18440479],
       [455337.71069731],
       [484024.77130672],
       [611135.46284773]])

In [68]:
df['Prediction']= np.round(pred, 1)

In [69]:
df

Area (sqr ft)  Bedroom  Age   Price  Prediction
0           2600      3.0   20  550000    551319.3
1           3000      4.0   15  565000    617860.7
2           3200      3.5   18  610000    605830.9
3           3600      3.0   30  595000    582201.5
4           4000      5.0    8  760000    723246.8
5           2200      2.0   10  510000    522869.6
6           1500      2.0    5  480000    496173.2
7           1000      2.0   10  500000    455337.7
8           1600      2.0   12  480000    484024.8
9           2700      4.0   11  600000    611135.5

In [70]:
from sklearn.metrics import r2_score

In [71]:
r2_score(y, pred)

0.8925103663538979

In [73]:
Area = int(input('Please enter the area of the building you want to buy')) 
Bedroom =int(input('Please enter the number of bedrooms of the building you want to buy')) 
Age = int(input('Please enter the age of the building you want to buy'))
np.round(model.predict([[Area, Bedroom, Age]]),1)

Please enter the area of the building you want to buy 2000
Please enter the number of bedrooms of the building you want to buy 2
Please enter the age of the building you want to buy 3


C:\Users\USER\miniconda3\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([[529390.3]])

In [74]:
from sklearn import metrics

In [76]:
MSE = metrics.mean_squared_error(y, pred)
MSE

689008551.6715142

In [77]:
RMSE = np.sqrt(MSE)
RMSE

26248.9723926769

In [78]:
from sklearn.linear_model import Ridge
ridge = Ridge(alpha = 3)
ridge.fit(X,y)

Ridge(alpha=3)

In [79]:
ridge.predict(X)

array([[547197.90392451],
       [608476.6630417 ],
       [607018.83690455],
       [588842.81321129],
       [723367.71563207],
       [539591.6721219 ],
       [503283.89864588],
       [446679.7591261 ],
       [485979.37864872],
       [599561.3587433 ]])

In [80]:
ridge.score(X,y)

0.8816911861252301

In [82]:
from sklearn.linear_model import Lasso
lasso = Lasso(alpha = 3)
lasso.fit(X,y)


Lasso(alpha=3)

In [83]:
lasso.predict(X)

array([551316.50656911, 617853.39207538, 605831.94007211, 582207.38971794,
       723246.26459171, 522882.35316427, 496178.3706799 , 455331.10770453,
       484026.36615421, 611126.30927083])

In [84]:
lasso.score(X,y)

0.8925103598520852